---
title: 'Exercise 1: Basic Data Manipulation'
author: "Aaron Lopez"
date: "4/9/2017"
output: html_document
---

## Load libraries and data
```{r, message=FALSE} 

library(dplyr)
library(tidyr)
refine_original <- read.csv("refine_original.csv")
refine_cleaning <- tbl_df(refine_original)

```

## 1: Clean up brand names

```{r}

refine_cleaning$company[1:6] = "philips"
refine_cleaning$company[7:13] = "akzo"
refine_cleaning$company[14:16] = "philips"
refine_cleaning$company[17:21] = "van houten"
refine_cleaning$company[22:25] = "unilever"

```

## 2: Separate produce code and number

```{r}

refine_cleaning <- separate(refine_cleaning, "Product.code...number", c("product_code", "product_number"), sep = "-")

```

## 3: Add product categories

```{r}

products <- c("Smartphone", "TV", "Laptop", "Tablet")
product_code <- c("p","v","x","q")
product_df <- data_frame(products, product_code)
refine_cleaning <- left_join(refine_cleaning, product_df, by="product_code")

```

## 4: Add full address for geocoding

```{r}

refine_cleaning <- unite(refine_cleaning, full_address, address, city, country, sep = ", ", remove = FALSE)

```
## 5: Create dummy variables for company and product category
```{r}

refine_cleaning <- mutate(refine_cleaning, company_philips = as.numeric(company == 'philips'))
refine_cleaning <- mutate(refine_cleaning, company_akzo = as.numeric(company == 'akzo'))
refine_cleaning <- mutate(refine_cleaning, company_van_houten = as.numeric(company == 'van houten'))
refine_cleaning <- mutate(refine_cleaning, company_unilever = as.numeric(company == 'unilever'))
refine_cleaning <- mutate(refine_cleaning, product_smartphone = as.numeric(products == 'Smartphone'))
refine_cleaning <- mutate(refine_cleaning, product_tv = as.numeric(products == 'TV'))
refine_cleaning <- mutate(refine_cleaning, product_laptop = as.numeric(products == 'Laptop'))
refine_cleaning <- mutate(refine_cleaning, product_tablet = as.numeric(products == 'Tablet'))

```
## 6: Submit to github original and cleaned up .csv files
```{r}

refine_clean <- refine_cleaning
write.csv(refine_clean, file = "refine_clean.csv")

```

