---
title: 'Exercise #2'
author: "Aaron Lopez"
date: "4/13/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## 0: Load libraries and data
```{r, message=FALSE}
library(dplyr)
library(tidyr)
titanic_original <- read.csv("titanic_original.csv")
titanic_cleaning <- tbl_df(titanic_original)
```
## 1: Port of embarkation
```{r}
titanic_cleaning[titanic_cleaning == ''] <- NA
titanic_cleaning <- replace_na(titanic_cleaning, list(embarked = "S"))
```
## 2: Age
```{r}
mean_age <- titanic_cleaning$age %>% na.exclude() %>% mean()
titanic_cleaning <- replace_na(titanic_cleaning, list(age = mean_age))
```
## 3: Lifeboat
##### In question 1 df was updated to replace all blanks with NA (titanic_cleaning[titanic_cleaning == ''] <- NA)

## 4: Cabin
```{r}
titanic_cleaning <- mutate(titanic_cleaning, has_cabin_number = as.numeric(cabin == ''))
titanic_cleaning$has_cabin_number[is.na(titanic_cleaning$has_cabin_number)] <- 1
```
## 5: Submit final .csv
```{r}
titanic_clean <- titanic_cleaning
write.csv(titanic_clean, file = "titanic_clean.csv")
```

